### ISSUE TITLE
problem when running the LeiModeler.exe

### ISSUE THREAD

**Issue by lelleMU** [lemonhi/modeling#1]
I ran the LeiModeler.exe in the binaryfile but it failed with a windows telling me that it failed to run because it couldn't find boost_chrono-vc100-mt-1_54.dll. So I compiled the boost1.54 library with vs2010 and put the needed dll file into the binaryfile but it still couldn't work. It just told me it failed without any other clues.

**Comment by lelleMU** [comment]
> I ran the LeiModeler.exe in the binaryfile but it failed with a windows telling me that it failed to run because it couldn't find boost_chrono-vc100-mt-1_54.dll. So I compiled the boost1.54 library with vs2010 and put the needed dll file into the binaryfile but it still couldn't work. It just told me it failed without any other clues.

OK I solved this by adding a 64-bit version boost_chrono-vc100-mt-1_54.dll

**Comment by yidahuang** [comment]
@lelleMU, hi, can u share the 64-version .dll, I met the same problem (:
